# -*- coding: utf-8 -*-
"""Copy of Renuka_Master_Thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1YG4_M2_KdRdzZ9ERVlFt3pkgZCPnmN

Drive

1. Environment Setup
"""

import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

print("Model loaded successfully")

# Commented out IPython magic to ensure Python compatibility.
# =========================
# MASTER SETUP CELL
# =========================

# Install libraries
pip install sentence-transformers rank_bm25 transformers

# Imports
import json
import numpy as np
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Clone repo if not exists
import os
if not os.path.exists("/content/ml-qrecc"):
git clone https://github.com/apple/ml-qrecc.git

# Move to folder
# %cd /content/ml-qrecc

# Unzip dataset (only if not already)
if not os.path.exists("dataset/qrecc_train.json"):
 unzip dataset/qrecc_data.zip -d dataset/

# Load dataset
with open("dataset/qrecc_train.json", "r") as f:
    train_data = json.load(f)

with open("dataset/qrecc_test.json", "r") as f:
    test_data = json.load(f)

# Build corpus
corpus = [item["Answer"] for item in train_data if item["Answer"]]

# Load embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

print("✅ Setup complete")
print("Train size:", len(train_data))
print("Corpus size:", len(corpus))

"""Dataset"""

import json

# Make sure path is correct
with open("/content/ml-qrecc/dataset/qrecc_train.json", "r") as f:
    train_data = json.load(f)

with open("/content/ml-qrecc/dataset/qrecc_test.json", "r") as f:
    test_data = json.load(f)

print("Train size:", len(train_data))
print("Test size:", len(test_data))

""" Corpus"""

corpus = []

for item in train_data:
    # Add context
    if item["Context"]:
        corpus.extend(item["Context"])

    # Add answer
    if item["Answer"]:
        corpus.append(item["Answer"])

print("Corpus size:", len(corpus))

"""5. Semantic Retrieval Setup (SBERT Embeddings)"""

from sentence_transformers import SentenceTransformer

embedder = SentenceTransformer("all-MiniLM-L6-v2")

subset_corpus = corpus[:5000]

corpus_embeddings = embedder.encode(
    subset_corpus,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

"""4. BM25 Retrieval Setup (Lexical Retriever)"""

from rank_bm25 import BM25Okapi

tokenized_corpus = [doc.lower().split() for doc in subset_corpus]
bm25 = BM25Okapi(tokenized_corpus)

"""9. Evaluation Metrics (F1 Score)"""

def compute_f1(pred, gold):
    pred_tokens = pred.lower().split()
    gold_tokens = gold.lower().split()

    common = set(pred_tokens) & set(gold_tokens)

    if len(common) == 0:
        return 0

    precision = len(common) / len(pred_tokens)
    recall = len(common) / len(gold_tokens)

    return 2 * (precision * recall) / (precision + recall)


def evaluate_model(data, model_fn, n=50):
    total_f1 = 0

    for sample in data[:n]:
        result = model_fn(sample)
        total_f1 += compute_f1(result["prediction"], result["gold"])

    return {"F1": total_f1 / n}

"""10. Evaluation Pipeline

"""

def evaluate_model(data, model_fn, n=50):
    total_f1 = 0

    for sample in data[:n]:
        result = model_fn(sample)
        total_f1 += compute_f1(result["prediction"], result["gold"])

    return {"F1": total_f1 / n}

"""7. Query Rewriting Module"""

def rewrite_query(question, context):
    memory = " ".join(context[-3:]) if context else ""

    prompt = f"""
    Rewrite the question using the conversation context.

    Context: {memory}
    Question: {question}
    Rewritten Question:
    """

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=50)

    rewritten = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return rewritten

"""13. Hybrid RAG Pipeline (FULL SYSTEM)"""

def compress_memory(context):
    if not context:
        return ""

    text = " ".join(context[-5:])  # take last 5 turns

    prompt = f"""
Summarize the following conversation briefly in 1-2 sentences:

{text}
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=60)

    summary = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return summary

def hybrid_rag(sample):
    question = sample["Question"]
    context = sample["Context"]
    compressed_context = compress_memory(context)

    # rewrite
    query = rewrite_query(question, compressed_context)

    # retrieval
    tokenized_query = query.lower().split()
    bm25_scores = bm25.get_scores(tokenized_query)

    query_embedding = embedder.encode([query], convert_to_numpy=True)[0]
    sbert_scores = np.dot(corpus_embeddings, query_embedding)

    bm25_scores = bm25_scores / (bm25_scores.max() + 1e-6)
    sbert_scores = sbert_scores / (sbert_scores.max() + 1e-6)

    combined_scores = 0.5 * bm25_scores + 0.5 * sbert_scores

    top_indices = np.argsort(combined_scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    # generation
    prompt = f"""
You are a helpful assistant. Answer the question using ONLY the provided context.

Give a clear, complete, and informative answer (1-2 sentences).

Context:
{retrieved}

Question:
{question}

Answer:
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=100)

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {
        "prediction": answer,
        "gold": sample["Answer"]
    }

test_output = hybrid_rag(test_data[0])
print(type(test_output))
print(test_output)

"""STEP 1 — Proper Baseline (RQ1 FIX)

11. Baseline Model (RQ1 – History Concatenation)
"""

def baseline_concat_rag(sample):
    question = sample["Question"]
    context = sample["Context"]

    # FULL history concatenation
    full_query = " ".join(context) + " " + question if context else question

    tokenized_query = full_query.lower().split()
    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    prompt = f"""
Context:
{retrieved}

Question:
{question}

Answer:
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=100)

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {
        "prediction": answer,
        "gold": sample["Answer"]
    }

def hybrid_no_memory(sample):
    question = sample["Question"]

    # NO context used
    query = question

    tokenized_query = query.lower().split()
    bm25_scores = bm25.get_scores(tokenized_query)

    query_embedding = embedder.encode([query], convert_to_numpy=True)[0]
    sbert_scores = np.dot(corpus_embeddings, query_embedding)

    bm25_scores = bm25_scores / (bm25_scores.max() + 1e-6)
    sbert_scores = sbert_scores / (sbert_scores.max() + 1e-6)

    combined_scores = 0.5 * bm25_scores + 0.5 * sbert_scores

    top_indices = np.argsort(combined_scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    prompt = f"""
You are a helpful assistant.

Context:
{retrieved}

Question:
{question}

Answer:
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=100)

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {
        "prediction": answer,
        "gold": sample["Answer"]
    }

def baseline_rag(sample):
    # No rewriting or memory compression
    question = sample["Question"]
    context = " ".join(sample["Context"]) if sample["Context"] else ""
    query = f"{context} {question}"

    # BM25+SBERT hybrid retrieval as before
    tokenized_query = query.lower().split()
    bm25_scores = bm25.get_scores(tokenized_query)
    query_embedding = embedder.encode([query], convert_to_numpy=True)[0]
    sbert_scores = np.dot(corpus_embeddings, query_embedding)
    bm25_scores /= (bm25_scores.max() + 1e-6)
    sbert_scores /= (sbert_scores.max() + 1e-6)
    combined_scores = 0.5 * bm25_scores + 0.5 * sbert_scores

    top_indices = np.argsort(combined_scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    prompt = f"Context: {retrieved}\nQuestion: {question}\nAnswer:"
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=100)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return {
        "prediction": answer,
        "gold": sample["Answer"]
    }

results_with_memory = evaluate_model(test_data, hybrid_rag, n=50)
results_no_memory = evaluate_model(test_data, hybrid_no_memory, n=50)

print("With Memory:", results_with_memory)
print("No Memory:", results_no_memory)

baseline_results = evaluate_model(test_data, baseline_rag, n=50)
hybrid_results = evaluate_model(test_data, hybrid_rag, n=50)

print("Baseline F1:", baseline_results["F1"])
print("Hybrid RAG F1:", hybrid_results["F1"])

print(type(train_data))
print(len(corpus))
print(len(subset_corpus))
print(corpus_embeddings.shape)
print(type(bm25))
print(type(hybrid_rag))

results = evaluate_model(test_data, hybrid_rag, n=50)
print(results)

"""8. Memory Compression Module (RQ2)"""

def compress_memory(context):
    if not context:
        return ""

    text = " ".join(context[-5:])  # take last 5 turns

    prompt = f"""
Summarize the following conversation briefly in 1-2 sentences:

{text}
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=60)

    summary = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return summary

"""🔵 12. Retrieval + Generation (No Rewriting)"""

def rag_no_rewrite(sample):
    question = sample["Question"]

    tokenized_query = question.lower().split()
    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    prompt = f"""
Context:
{retrieved}

Question:
{question}

Answer:
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=100)

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {
        "prediction": answer,
        "gold": sample["Answer"]
    }

"""14. Retrieval Only (RQ3 Ablation)"""

def retrieve_only(sample):
    question = sample["Question"]

    tokenized_query = question.lower().split()
    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[::-1][:5]
    retrieved = " ".join([subset_corpus[i] for i in top_indices])

    return {
        "prediction": retrieved,
        "gold": sample["Answer"]
    }

"""15. Final Evaluation (ALL MODELS)"""

print("Baseline (Concat):", evaluate_model(test_data, baseline_concat_rag, n=50))
print("No Rewrite:", evaluate_model(test_data, rag_no_rewrite, n=50))
print("Hybrid (Full):", evaluate_model(test_data, hybrid_rag, n=50))
print("Retrieve Only:", evaluate_model(test_data, retrieve_only, n=50))

"""16. VISUALIZATION & ANALYSIS

Chart 1 — Model Comparison
"""

import matplotlib.pyplot as plt

models = ["Retrieve Only", "Baseline", "No Rewrite", "Hybrid"]
scores = [0.0238, 0.0306, 0.0419, 0.0469]

plt.figure()
plt.bar(models, scores)
plt.xlabel("Models")
plt.ylabel("F1 Score")
plt.title("Model Performance Comparison")
plt.xticks(rotation=30)
plt.show()

"""Chart 2 — Component Contribution (RQ3)"""

components = ["Retrieval", "Generation", "Rewrite+Memory"]
scores = [0.0238, 0.0419, 0.0469]

plt.figure()
plt.plot(components, scores, marker='o')
plt.xlabel("System Components")
plt.ylabel("F1 Score")
plt.title("Contribution of Each Component")
plt.show()

"""Chart 3 — Memory Impact (RQ2)"""

labels = ["No Memory", "With Memory"]
scores = [0.0391, 0.0466]

plt.figure()
plt.bar(labels, scores)
plt.xlabel("Memory Usage")
plt.ylabel("F1 Score")
plt.title("Impact of Memory Compression")
plt.show()

"""Chart 4 — Baseline vs Final (RQ1)"""

labels = ["Baseline", "Hybrid"]
scores = [0.0306, 0.0469]

plt.figure()
plt.bar(labels, scores)
plt.xlabel("Models")
plt.ylabel("F1 Score")
plt.title("Baseline vs Hybrid Model")
plt.show()

"""Dashboard Power BI"""

import pandas as pd

data = {
    "Model": ["Retrieve Only", "Baseline", "No Rewrite", "Hybrid"],
    "F1 Score": [0.0238, 0.0306, 0.0419, 0.0469]
}

df = pd.DataFrame(data)
df.to_csv("results.csv", index=False)

df

from google.colab import files
files.download("results.csv")

import streamlit as st
import matplotlib.pyplot as plt

st.title("Conversational QA System Dashboard")

st.write("This dashboard shows the performance of different models.")

# Data
models = ["Retrieve Only", "Baseline", "No Rewrite", "Hybrid"]
scores = [0.0238, 0.0306, 0.0419, 0.0469]

# Chart
fig, ax = plt.subplots()
ax.bar(models, scores)
ax.set_ylabel("F1 Score")
ax.set_title("Model Performance")

st.pyplot(fig)

# Explanation
st.subheader("Key Insights")

st.write("""
- Hybrid model performs best
- Query rewriting improves results
- Memory helps in understanding context
- Retrieval alone is not sufficient
""")

# Simple input demo
st.subheader("Ask a Question (Demo)")

question = st.text_input("Enter your question:")

if question:
    st.write("Model Response (demo):")
    st.write("This is where your model output will appear.")

